"""add_media_fields_to_projects

Revision ID: 0e15539d7806
Revises: 2cbb85c1a867
Create Date: 2025-07-23 01:04:03.703026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e15539d7806'
down_revision = '2cbb85c1a867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add columns that don't exist yet
    op.add_column('projects', sa.Column('zip_urls', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('pdf_urls', sa.Text(), nullable=True))
    # video_urls, thumbnail_url, and external_collaborators already exist in DB
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop columns we added in upgrade
    op.drop_column('projects', 'pdf_urls')
    op.drop_column('projects', 'zip_urls')
    # ### end Alembic commands ###
