"""Add CV fields back to User model

Revision ID: 458739114073
Revises: e2752ba6d061
Create Date: 2025-07-30 08:34:29.957535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458739114073'
down_revision = 'e2752ba6d061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cv_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cv_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cv_uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cv_uploaded_at')
        batch_op.drop_column('cv_file_id')
        batch_op.drop_column('cv_summary')
        batch_op.drop_column('cv_url')

    # ### end Alembic commands ###
