"""Remove is_in_stock column from merchandise table

Revision ID: 4c64b1c85b02
Revises: 7573e95a6c59
Create Date: 2025-07-25 17:04:25.321262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c64b1c85b02'
down_revision = '7573e95a6c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.drop_column('is_in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_stock', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
