"""remove_image_urls_from_projects

Revision ID: 503ccb42ac88
Revises: 0e15539d7806
Create Date: 2025-07-23 01:09:53.443266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503ccb42ac88'
down_revision = '0e15539d7806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
