"""Add quantity field to merchandise and hidden_from_user to orders

Revision ID: 7573e95a6c59
Revises: 9c1c209a0a41
Create Date: 2025-07-25 16:37:58.773260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7573e95a6c59'
down_revision = '9c1c209a0a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_from_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('hidden_from_user')

    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
