"""Add contributions feature and update user model

Revision ID: f84afb8bbf90
Revises: 18cb84bc5749
Create Date: 2025-07-29 13:15:03.883080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f84afb8bbf90'
down_revision = '18cb84bc5749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_projects_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['users_projects_id'], ['users_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('documentation_file_id')
        batch_op.drop_column('project_summary')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.drop_column('cv_url')
        batch_op.drop_column('cv_file_id')
        batch_op.drop_column('cv_summary')
        batch_op.drop_column('cv_uploaded_at')

    with op.batch_alter_table('users_projects', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_projects', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cv_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cv_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cv_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('company')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('documentation_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('contributions')
    # ### end Alembic commands ###
